# -*- coding: utf-8 -*-
"""Instagram Recap Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSvXHZN8G0inmjkxI-cwGKYu11KnCGay
"""

import json
import os
from collections import Counter
from datetime import datetime

def generate_recap(json_file):
    # 1. Load the data
    with open(json_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    messages = data.get('messages', [])

    # 2. Extract Basic Stats
    total_messages = len(messages)
    senders = [m.get('sender_name', 'Unknown') for m in messages]
    sender_counts = Counter(senders)

    # 3. Find the "MVP" (Most active person)
    top_sender, top_count = sender_counts.most_common(1)[0]

    # 4. Process timestamps for "Peak Activity"
    # Instagram timestamps are in milliseconds
    hours = [datetime.fromtimestamp(m['timestamp_ms']/1000).hour for m in messages]
    peak_hour = Counter(hours).most_common(1)[0][0]
    ampm = "PM" if peak_hour >= 12 else "AM"
    display_hour = peak_hour if peak_hour <= 12 else peak_hour - 12
    if display_hour == 0: display_hour = 12

    # 5. Create the HTML Report
    # We use a f-string to inject our Python variables into the HTML template
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Group Chat Recap</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
            body {{ background: linear-gradient(135deg, #833ab4, #fd1d1d, #fcb045); min-height: 100vh; color: white; }}
            .card {{ background: rgba(255, 255, 255, 0.15); backdrop-filter: blur(10px); border-radius: 20px; }}
        </style>
    </head>
    <body class="p-8 font-sans">
        <div class="max-w-2xl mx-auto text-center">
            <h1 class="text-5xl font-extrabold mb-4">Yearly Recap</h1>
            <p class="text-xl opacity-90 mb-12">Our digital footprint in numbers</p>

            <div class="grid grid-cols-1 gap-6">
                <!-- Main Stat -->
                <div class="card p-8">
                    <h2 class="text-sm uppercase tracking-widest opacity-70">Total Messages</h2>
                    <p class="text-6xl font-bold mt-2">{total_messages}</p>
                </div>

                <!-- MVP Stat -->
                <div class="card p-8 border-2 border-yellow-400">
                    <h2 class="text-sm uppercase tracking-widest opacity-70">The Chat Legend</h2>
                    <p class="text-4xl font-bold mt-2">{top_sender}</p>
                    <p class="text-lg opacity-80">{top_count} messages sent</p>
                </div>

                <!-- Leaderboard -->
                <div class="card p-8 text-left">
                    <h2 class="text-xl font-bold mb-4 border-b border-white/20 pb-2">Top Messengers</h2>
                    <ul>
                        { "".join([f'<li class="flex justify-between py-2 border-b border-white/10"><span>{name}</span><span class="font-bold">{count}</span></li>' for name, count in sender_counts.most_common(5)]) }
                    </ul>
                </div>

                <!-- Time Stat -->
                <div class="card p-6">
                    <p class="text-lg">The group is most active around <span class="font-bold text-2xl">{display_hour} {ampm}</span></p>
                </div>
            </div>

            <footer class="mt-12 text-sm opacity-60">
                Generated via Python • Stay Toxic
            </footer>
        </div>
    </body>
    </html>
    """

    # Write the result to index.html
    with open('index.html', 'w', encoding='utf-8') as f:
        f.write(html_content)

    print("✨ Success! Open 'index.html' in your browser to see your recap.")

if __name__ == "__main__":
    # Ensure the file exists before running
    if os.path.exists('message_1.json'):
        generate_recap('message_1.json')
    else:
        print("Error: Could not find message_1.json in this folder.")